In [1]:
import pandas as pd
import numpy as np
import seaborn as sns                       #visualisation
import matplotlib.pyplot as plt             #visualisation
%matplotlib inline     
sns.set(color_codes=True)

In [2]:
# EXCEL
path = 'excel_ordenado.xlsx'

df = pd.read_excel(path)#, index_col='objectid')
# si luego de pd.real_excel(path, , index_col='Datos') , index_col='NameColumn'significa que indexa las filas segun el valor de alguna columna
df

C:\Users\ACER NITRO 5\AppData\Roaming\Python\Python39\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,APELLIDO,NOMBRE_COMPLETO,NOMBRE,DNI,PRODUCTO,CALLE,DIRECCION,NUMERO,DEPARTAMENTO,BARRIO,CONTACTO,OBSERVACIONES,FECHA
0,RODAS,RODAS ROXANA,ROXANA,20622020.0,3 FRAZADAS,PETRONA ROSENDA DE SIERRA,PETRONA ROSENDA DE SIERRA 2050,2050.0,NaN,LICEO GENERAL PAZ,3516002935.0,RAUL,2022-07-01 03:00:00
1,RODRIGUEZ,RODRIGUEZ ROMINA,ROMINA,31057427.0,"1 MODULO,1 BOLSA DE FRESCOS,1 BOLSA DE VERDURA...",SINSACATE,SINSACATE 2920.0,2920.0,NaN,YAPEYU,3513150083.0,SECRETARIA,2022-07-01 03:00:00
2,SUAREZ,SUAREZ LUIS,LUIS,24073589.0,3 PACKS DE AGUA X 500 ML.,CLUB YAPEYU,CLUB YAPEYU,NaN,NaN,NaN,NaN,SECRETARIA,2022-07-01 03:00:00
3,ANGELO,ANGELO ELIANA ANDREA,ELIANA ANDREA,23231601.0,"1 MODULO,1 KIT,1 BOLSA DE VERDURA,1 BOLSA DE F...",JUAN CARLOS AVALOS,JUAN CARLOS AVALOS 29.0,29.0,NaN,BAJO GENERAL PAZ,3512151253.0,SECRETARIA-CECI,2022-07-01 03:00:00
4,ESPINOSA,ESPINOSA DEBORA,DEBORA,27959735.0,1 KIT DE OLLAS,MZA 25 LOTE 17,MZA 25 LOTE 17,NaN,NaN,CIUDAD DE MIS SUEÑOS,3513228884.0,ANDREA-RAUL,2022-07-01 03:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,CORTEZ,CORTEZ ANA YANINA,ANA YANINA,34767742.0,"3 COLCHONES,3 FRAZADAS,3 MODULOS,2 KIT DE HIGI...",LUIS AGOTE,LUIS AGOTE 3773.0,3773.0,NaN,LOS GRANADOS,35156451993.0,SECRETARIA-CECI,2022-08-25 03:00:00
373,ROLDAN,ROLDAN BRENDA,BRENDA,41152709.0,"1 KIT DE HIGIENE,1 MODULO,4 FRAZADAS,2 COLCHON...",PASAJE 20 DE JUNIO,PASAJE 20 DE JUNIO 58.0,58.0,NaN,LOS FILTROS,3515159491.0,APP,2022-08-26 03:00:00
374,PONTICOVA,PONTICOVA WALTER,WALTER,24172552.0,"50 MAPAS,100 HULA HULA,30 PELOTAS,30 PINGPONG,...",FRUCTUOSO RIVERA,FRUCTUOSO RIVERA 1237.0,1237.0,NaN,OBSERVATORIO,3512228502.0,LILI MONTERO,2022-08-29 03:00:00
375,FARIAS,FARIAS JOSE RUBEN,JOSE RUBEN,39253113.0,40 MODULOS,CAMARGO LOAYZA,CAMARGO LOAYZA 2850.0,2850.0,NaN,JOSE IGNACIO DIAZ II,3513633867.0,SECRETARIA-CECI,2022-08-30 03:00:00
376,URSALIAN,URSALIAN ALICIA,ALICIA,6492759.0,20 MODULOS,MANUEL DORREGO ESQ CENTRO AMERICA,MANUEL DORREGO ESQ CENTRO AMERICA 1853.0,1853.0,NaN,JUNIORS,3515920100.0,SECRETARIA-CECI,2022-08-31 03:00:00

In [5]:
#LIMPIANDO CARACTERES ESPECIALES

L_calle = 'NOMBRE_COMPLETO'

df[L_calle] = df[L_calle].str.replace('Ñ','N',regex = True)
df[L_calle] = df[L_calle].str.replace('Á','A',regex = True)
df[L_calle] = df[L_calle].str.replace('É','E',regex = True)
df[L_calle] = df[L_calle].str.replace('Í','I',regex = True)
df[L_calle] = df[L_calle].str.replace('Ó','O',regex = True)
df[L_calle] = df[L_calle].str.replace('Ú','U',regex = True)
df[L_calle] = df[L_calle].str.replace('Ü','U',regex = True)
df[L_calle] = df[L_calle].str.replace('á','a',regex = True)
df[L_calle] = df[L_calle].str.replace('é','e',regex = True)
df[L_calle] = df[L_calle].str.replace('í','i',regex = True)
df[L_calle] = df[L_calle].str.replace('ó','o',regex = True)
df[L_calle] = df[L_calle].str.replace('ú','u',regex = True)
df[L_calle] = df[L_calle].str.replace('ñ','n',regex = True)
#df[L_calle] = df[L_calle].str.replace('[/]',' ',regex = True)
#df[L_calle] = df[L_calle].str.replace('[-(><!#$:)/.;,?¢¶âš™äëöüÿ»&+#³Ïï¡☐¦‡•…□▭▯ðÿ·€—§-±¾ž“‘©°˜ðšÿ™â¤¥½œ¼£üç)]','',regex = True)
df

,APELLIDO,NOMBRE_COMPLETO,NOMBRE,DNI,PRODUCTO,CALLE,DIRECCION,NUMERO,DEPARTAMENTO,BARRIO,CONTACTO,OBSERVACIONES,FECHA
0,RODAS,RODAS ROXANA,ROXANA,20622020.0,3 FRAZADAS,PETRONA ROSENDA DE SIERRA,PETRONA ROSENDA DE SIERRA 2050,2050.0,NaN,LICEO GENERAL PAZ,3516002935.0,RAUL,2022-07-01 03:00:00
1,RODRIGUEZ,RODRIGUEZ ROMINA,ROMINA,31057427.0,"1 MODULO,1 BOLSA DE FRESCOS,1 BOLSA DE VERDURA...",SINSACATE,SINSACATE 2920.0,2920.0,NaN,YAPEYU,3513150083.0,SECRETARIA,2022-07-01 03:00:00
2,SUAREZ,SUAREZ LUIS,LUIS,24073589.0,3 PACKS DE AGUA X 500 ML.,CLUB YAPEYU,CLUB YAPEYU,NaN,NaN,NaN,NaN,SECRETARIA,2022-07-01 03:00:00
3,ANGELO,ANGELO ELIANA ANDREA,ELIANA ANDREA,23231601.0,"1 MODULO,1 KIT,1 BOLSA DE VERDURA,1 BOLSA DE F...",JUAN CARLOS AVALOS,JUAN CARLOS AVALOS 29.0,29.0,NaN,BAJO GENERAL PAZ,3512151253.0,SECRETARIA-CECI,2022-07-01 03:00:00
4,ESPINOSA,ESPINOSA DEBORA,DEBORA,27959735.0,1 KIT DE OLLAS,MZA 25 LOTE 17,MZA 25 LOTE 17,NaN,NaN,CIUDAD DE MIS SUENOS,3513228884.0,ANDREA-RAUL,2022-07-01 03:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,CORTEZ,CORTEZ ANA YANINA,ANA YANINA,34767742.0,"3 COLCHONES,3 FRAZADAS,3 MODULOS,2 KIT DE HIGI...",LUIS AGOTE,LUIS AGOTE 3773.0,3773.0,NaN,LOS GRANADOS,35156451993.0,SECRETARIA-CECI,2022-08-25 03:00:00
373,ROLDAN,ROLDAN BRENDA,BRENDA,41152709.0,"1 KIT DE HIGIENE,1 MODULO,4 FRAZADAS,2 COLCHON...",PASAJE 20 DE JUNIO,PASAJE 20 DE JUNIO 58.0,58.0,NaN,LOS FILTROS,3515159491.0,APP,2022-08-26 03:00:00
374,PONTICOVA,PONTICOVA WALTER,WALTER,24172552.0,"50 MAPAS,100 HULA HULA,30 PELOTAS,30 PINGPONG,...",FRUCTUOSO RIVERA,FRUCTUOSO RIVERA 1237.0,1237.0,NaN,OBSERVATORIO,3512228502.0,LILI MONTERO,2022-08-29 03:00:00
375,FARIAS,FARIAS JOSE RUBEN,JOSE RUBEN,39253113.0,40 MODULOS,CAMARGO LOAYZA,CAMARGO LOAYZA 2850.0,2850.0,NaN,JOSE IGNACIO DIAZ II,3513633867.0,SECRETARIA-CECI,2022-08-30 03:00:00
376,URSALIAN,URSALIAN ALICIA,ALICIA,6492759.0,20 MODULOS,MANUEL DORREGO ESQ CENTRO AMERICA,MANUEL DORREGO ESQ CENTRO AMERICA 1853.0,1853.0,NaN,JUNIORS,3515920100.0,SECRETARIA-CECI,2022-08-31 03:00:00

In [6]:
# Esta línea permite descargar el archivo ya limpio en formato XLSX (si deseas descargarlo como CSV tendrás que indicarlo de la manera adecuada)
# Te lo guarda en la dirección donde esté alojado el script.

df.to_excel('JULIO-AGOSTO 2022_LIMPIO.xlsx')